CREATE TABLE fincas(`id` int(11) NOT NULL AUTO_INCREMENT,
`codigo_finca` varchar(16),
`provincia` VARCHAR(512),
`canton`VARCHAR(512),
`parroquia` VARCHAR(512),
`nombre_propietario` VARCHAR(512),
`telefono`INT(11),
`asociacion`VARCHAR(512),
`nombre_predio` VARCHAR(64),
`geopoint` VARCHAR(64),
`geopoint_latitude`DECIMAL(11,9),
`geopoint_longitude` DECIMAL(20,10),
`geopoint_altitude`DECIMAL(20,12),
`geopoint_precision` DECIMAL(11,2),
`info_coordenadaX`DECIMAL(10,4),
`info_coordenadaY` FLOAT(12,4),
`info_altitud` DECIMAL(10,6),
`fecha_registro` TIMESTAMP NOT NULL DEFAULT current_timestamp(),
PRIMARY KEY(`id`))ENGINE=InnoDB;